### ISSUE TITLE
Accessibility - Metro - TalkBack Issues with Occupation Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#15]
When I go from the main city screen to the "Occupational Employment and Wages" more details page there is issues with the drop-down after being activated. TalkBack announces "loading Seasonally adjusted data" or something like that. Other times it reads the content of the first cell in the TABLE.

This might be an issues with other screens that use a drop-down to change content in a similar fashion.

**Comment by greg-gruse** [comment]
I'm having problems reproducing this issue,  for me it always reads the loading seasonally adjusted message followed by the name of the screen in the top nav bar followed by home button which is the first selectable item on the screen.  I've also tested on a variety of different OS levels via the simulators.

These messages are somewhat timing sensitive in that audio will get kicked off and other changes may stop or delay it.  Also network download speeds can change how the messages are triggered.

I did change that message from "loading seasonally adjusted reports" to "loading reports" since the seasonally adjusted switch does not appear on that screen.

Can you give me any more suggestions on how to repeat the error?

**Comment by greg-gruse** [comment]
Can you give me any more suggestions on how to repeat this error?

**Comment by jfc3-dol** [comment]
TalkBack is now reading which item that was selected from the drop-down list instead of "loading Seasonally adjusted data". It's not now reading the first cell of the TABLE which might have been an accidental fat finger on my part the way I was holding the phone or tablet at the time that caused that issue.

Closing issue because TalkBack is not reading "loading Seasonally adjusted data" anymore.
