### ISSUE TITLE
Accessibility - Why Does Application Now Focus in Search Box

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Local-Labor-Market-Data-Android#17]
Why does the application now focus in the search box? I know this is not an Android issue because it didn't work this way previously.

It was focusing at the top of the application in the previous version. By doing so, you are attempting to force the user to search and having the keyboard visible for everyone.

On my phone, the keyboard takes up most of the screen which makes it difficult to see cities, states, or counties. 

Once focused in the search box the keyboard doesn't go away for the user unless they do a search which they might not want to do. Even if they switch from the metro tab to one of the other tabs the keyboard stays and a person can only see one item besides the Current Location, National, or County text/button.

Even when a user comes back to the screen from somewhere else in the application, it focuses in the search box and forces the keyboard to show.

**Comment by greg-gruse** [comment]
The application does not focus in the search on my device - this must be a device / os level issue, I will investigate.  Can you remind me the device / os level you are using?

There is another way to dismiss the keyboard on android - on the bottom of the screen the back button (one on the left) should dismiss the screen.   That being said I will make it so that the keyboard goes away when selecting one of the other tabs, I'll also dismiss it when the user navigates away from the screen.

**Comment by jfc3-dol** [comment]
We are using two devices for are testing and they are the following:

- Samsung Galaxy 7S running Android 7.0
- Samsung Galaxy Tab S running Android 6.0.1

**Comment by greg-gruse** [comment]
This is fixed in the next build.

**Comment by jfc3-dol** [comment]
When entering the application for the first time, it is now not focusing in the search box and showing the keyboard.

I'm going to close this issue.
